code/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
# from rest_framework.aut
from api import views

app_name = 'api'

router = DefaultRouter()

router.register('unitmeasure', viewset=views.UnitMeasureMVS, basename='unitmeasure')
router.register('status', viewset=views.StatusMVS, basename='status')
router.register('people', viewset=views.PeopleMVS, basename='people')
router.register('attachment', viewset=views.AttachmentMVS, basename='attachment')
router.register('partcategory', viewset=views.PartCategoryMVS, basename='partcategory')
router.register('supplier', viewset=views.SupplierMVS, basename='supplier')
router.register('part',viewset=views.PartMVS, basename='part')
router.register('minstock', viewset=views.MinimumStockMVS, basename='minstock')
router.register('currentstock', viewset=views.CurrentStockMVS, basename='currentstock')
router.register('order', viewset=views.OrderMVS, basename='order')
router.register('receiving', viewset=views.ReceivingMVS, basename='receiving')
router.register('dash', viewset=views.Dash, basename='dash')

urlpatterns = [
    path('', include(router.urls)),
    path('schema', get_schema_view(title='ERP API', description='RESTful API for the ERP web application'))
]

from rest_framework.authtoken import views
urlpatterns += [
    path('auth-token/', views.obtain_auth_token)
]

code/erpWa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include('frontend.urls')),
    path('api/', include('api.urls')),
    path('api/docs', include_docs_urls(title="ERP web app API"))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path ('media/<path:path>', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

code/frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from frontend import views


app_name = 'frontend'

urlpatterns = [
    path('logout', views.logoutRedirect, name='logoutRedirect'),
    path('', views.HomePage.as_view(), name='home'),
    path('current', views.CurrentStock.as_view(), name='currentHome'),
    path('current/update', views.CurrentStockUpdate.as_view(), name='currentUpdate'),
    path('current/upload', views.CurrentStockUpload.as_view(), name='currentUpload'),
    path('min', views.MinimumStock.as_view(), name='minHome'),
    path('min/update', views.MinStockUpdate.as_view(), name='minUpdate'),
    path('min/upload', views.MinimumStockUpload.as_view(), name='minUpload'),
    path('purchasing', views.Purchasing.as_view(), name='purchasingHome'),
    path('purchasing/create', views.PurchasingCreate.as_view(),
         name='purchasingCreate'),
    path('purchasing/update/<int:pk>',
         views.PurchaseUpdate.as_view(), name='purchasingUpdate'),
    path('purchasing/close', views.ClosePurchaseOrder.as_view(),
         name='purchasingClose'),
    path('purchasing/open/<int:pk>',
         views.OpenPurchaseOrder.as_view(), name='purchasingOpen'),
    path('purchasing/delete', views.DeletePurchaseOrder.as_view(),
         name='purchaseDelete'),
    path('purchasing/edit', views.EditPurchaseOrder.as_view(), name='purchaseEdit'),

    path('workingonit', TemplateView.as_view(
        template_name='inprogress/underWork.html'), name='inprog'),

    path('test', (TemplateView.as_view(
        template_name='registration/login_test.html')), name='test'),
    path('workingonit', TemplateView.as_view(
        template_name='inprogress/underWork_normal.html'), name='inprog')
]

code/frontend/models.py
from django.db import models

# Create your models here.

code/frontend/views.py
import requests
from utils.utils import csvread
import json
import time
from django.urls import reverse, resolve, reverse_lazy
# from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from utils.apiUtils import api_get, api_auth, api_post, api_patch, api_delete
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
decorators=[never_cache,]

# Create your views here.


def logoutRedirect(request):
    # print(request)
    logout(request=request)
    
    return HttpResponseRedirect(redirect_to=reverse('frontend:home'))

# Homepage

class HomePage(LoginRequiredMixin, View):
    # redirect_field_name = 'redirect_to'
    template_name = 'home/dash.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'module':'Dashboard'}
        
        return render(request, template_name=self.template_name, context=data)

class CurrentStock(LoginRequiredMixin, View):
    template_name = 'current/current.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')
    

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet

       

        data ={
            'dash':dashGet.json(),
            'types':typeGet.json(),
            'module':'Current Stock'}
        
        return render(request, template_name=self.template_name, context=data)

class CurrentStockUpdate(LoginRequiredMixin, View):

    def get(self,request):
        return redirect(to=reverse_lazy('frontend:currentHome'))

    def post(self,request):

        partUrl = request.build_absolute_uri(reverse_lazy('api:part-list'))
        partGet = api_get(url= partUrl, request= request)
        partData = partGet.json()

        updateQuantity = request.POST.getlist('new_quantity')

        apiPostData = []

        for count,val in enumerate(updateQuantity):
            if val != "":
                apiPostData.append({
                    'part': partData[count]['url'],
                    'currentStock': int(val)
                })

        currentStockUrl = request.build_absolute_uri(reverse_lazy('api:currentstock-list'))

        apiPost =api_post(
            url= currentStockUrl,
            data=json.dumps(apiPostData),
            request=request,
            post_content_type='json'
            )
        
        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:currentHome'))

class CurrentStockUpload(LoginRequiredMixin, View):

    def post(self,request):
        
        reader = csvread(request=request,form_handle='file')
        current_post = []
        for row in reader:
            if row[2] != "":
                current_post.append(
                {
                    "part": row[0],
                    "currentStock": row[2]
                }
                )
        current_post.pop(0)
        # print(json.dumps(current_post))
        
        api = request.build_absolute_uri(reverse_lazy('api:currentstock-list'))
        
        apiPost = api_post(url= api, request=request, data= json.dumps(current_post), post_content_type='json')

        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:currentHome'))


class MinimumStock(LoginRequiredMixin, View):
    template_name = 'min/min.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'module':'Minimum Stock'}
        
        return render(request, template_name=self.template_name, context=data)

class MinStockUpdate(LoginRequiredMixin, View):

    def get(self,request):
        return redirect(to=reverse_lazy('frontend:minHome'))

    def post(self,request):
        # print(request.POST)

        partUrl = request.build_absolute_uri(reverse_lazy('api:part-list'))
        partGet = api_get(url= partUrl, request= request)
        partData = partGet.json()

        updateQuantity = request.POST.getlist('new_quantity')

        apiPostData = []

        for count,val in enumerate(updateQuantity):
            if val != "":
                apiPostData.append({
                    'part': partData[count]['url'],
                    'minimumStock': int(val)
                })

        # print(apiPostData)
        minStockUrl = request.build_absolute_uri(reverse_lazy('api:minstock-list'))

        apiPost =api_post(
            url= minStockUrl,
            data=json.dumps(apiPostData),
            request=request,
            post_content_type='json'
            )
        
        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:minHome'))

class MinimumStockUpload(LoginRequiredMixin, View):

    def post(self,request):
        
        reader = csvread(request=request,form_handle='file')
        current_post = []
        for row in reader:
            if row[2] != "":
                current_post.append(
                {
                    "part": row[0],
                    "minimumStock": row[2]
                }
                )
        current_post.pop(0)
        # print(json.dumps(current_post))
        
        api = request.build_absolute_uri(reverse_lazy('api:minstock-list'))
        
        apiPost = api_post(url= api, request=request, data= json.dumps(current_post), post_content_type='json')

        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:minHome'))


class Purchasing(LoginRequiredMixin, View):
    template_name= 'purchasing/main.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')
    orderEndpoint = reverse_lazy('api:order-list')

    def get(self, request):
        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        orderUrl = request.build_absolute_uri(self.orderEndpoint)
        orderGet = api_get(url=orderUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet
        if isinstance(orderGet, HttpResponse):
            return orderGet

        orderData = orderGet.json()

        
        total = len(orderData)
        delivered = 0
        undelivered =0
        for order in orderData:
            if order['dateDelivered']:
                delivered +=1
            elif order['dateDelivered'] is None:
                undelivered +=1
        
        orderSummary={
            'total' : total,
            'delivered' : delivered,
            'undelivered' : undelivered
        }


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'summary':orderSummary, 'module':'Purchasing'}
        
        return render(request, template_name=self.template_name, context=data)

@method_decorator(name='dispatch', decorator=never_cache)
class PurchasingCreate(LoginRequiredMixin,View):
    template_name = 'purchasing/createMain.html'
    orderEndpoint = reverse_lazy('api:order-list')
    partEndpoint = reverse_lazy('api:part-list')

    def get(self,request, extra=None):

        startTime = time.time()
        partUrl = request.build_absolute_uri(self.partEndpoint)
        partGet = api_get(url= partUrl, request=request)

        orderUrl = request.build_absolute_uri(self.orderEndpoint)
        orderGet =api_get(url=orderUrl, request=request)


        if isinstance(partGet, HttpResponse):
            return partGet

        if isinstance(orderGet, HttpResponse):
            return orderGet
        
        partData = partGet.json()
        orderData = orderGet.json()

        for dict in orderData:
            for pdict in partData:
                if pdict['url']== dict['part']:
                    dict['partName']= pdict['name']
            # print(dict['partName'])                

        
        data={
            'parts': partData,
            'orders': orderData
        }

        # print('!!!!!>>> Time: ', (time.time()-startTime))

code/frontend/templates/min/min.html
{%extends 'base/base.html'%}
{%block main_content%}
    <div class="row row_filter">
        <div class="col-lg-12 col_filter d-grid gap-2">
            {%include 'min/minFilters.html'%}
        </div>
    </div>
    <div class="row row_content">
        <div class="col-lg-6 col_content">
            {%include 'min/minTable.html'%}
        </div>
        <div class="col-lg-5 col_upload">
            {%include 'min/upload.html'%}
        </div>
    </div>
{%endblock main_content%}

code/frontend/templates/min/minFilters.html
    <div class="row">
        <div class="col-lg-2">
            <label for="fiPartName"><h4>Part Name</h4></label>
        </div>
        <div class="col-lg-4">
            <input type="text" placeholder="" id="fiPartName" class="form-control">
        </div>
    </div>

    <div class="row">
        <div class="col-lg-2">
            <label for="fiPartType"><h4>Part Type</h4></label>
        </div>
        <div class="col-lg-4">
            
            <select name="part_type" id="fiPartType" class="form-select" >
                <option value="" disabled selected hidden> </option>
                {%for type in types%}
                <option value="{{type.category}}">{{type.category | capfirst}}</option>
                {%endfor%}
            </select>
        </div>
    </div>

   

    <div class="row">
        <div class="col-lg-2 d-grid">
            <button class="btn btn-outline-primary" onclick="filter()">Search</button>
        </div>

        <div class="col-lg-5">
            <div class="btn-group" role="group" aria-label="filter_buttons">                        
                <a href="{%url 'frontend:minHome'%}" class="btn btn-outline-warning" id="revert"  >Revert</a>
                <button type="button" class="btn btn-outline-dark" id="export">Export</button>
            </div>
        </div>

        <div class="col-lg-5">
            <div class="btn-group" role="group" aria-label="update_buttons">
                <button class="btn btn-primary" onclick="update()">Update</button>
                <button class="btn btn-success" id="commit" onclick="update_check()">Commit</button>
                <button class="btn btn-warning" onclick="cell_clear()">Clear</button>

            </div>
        </div>

        
        
    </div>
{%load static%}
<script src="{%static 'min/filter.js'%}"></script>

code/frontend/templates/min/minTable.html
<table class="table table-dash">
    <thead>
        <th>Id</th>
        <th>Part Name</th>
        <th>Category</th>
        <th>Minimum Stock</th>

    </thead>
    <tbody>
        <form method="POST" action="{%url 'frontend:minUpdate'%}" id="min_update">
            {%csrf_token%}
            {%for inst in dash%}
            <tr class="table_row">
                <td class="t_id">{{inst.id}}</td>
                <td class="t_part_name">{{inst.name}}</td>
                <td class="t_part_type">{{inst.category | capfirst}}</td>
                <td class="t_min_stock">{{inst.minimumStock}}</td>
                <td>
                    <input id="new_input" class="t_ms_editable" style="display: none;" type="number" name="new_quantity" placeholder="{{inst.minimumStock}}" >
                </td>
            </tr>
            {%endfor%}

        </form>

    </tbody>
    
        

</table>

code/frontend/templates/min/upload.html
<div class="row bg-white box_shadow p-3">
    <div class="display-5 p-2 text-center"> Upload from a file </div>
    
    <form action="{%url 'frontend:minUpload'%}" method="post" id="file_form" class="d-grid gap-3 p-3" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="row g-3 pt-3 align-items-center">
            <div class="col-lg-4">
              
              <label for="file_upload" class="col-form-label fs-4"> 
                Please select a CSV file
                 </label>
    
            </div>
            <div class="col-lg-6">
              <input type="file" class="form-control" name="file" id="file">
            </div>
          </div>
        
    
    </form>

    <div class="row g-3 pt-3 align-items-center">
        <div class="col-lg-4 d-grid g-3">
            
            <button class="btn btn-primary btn-lg" id="button" onclick="file_check()">Upload</button>

        </div>
    </div>
</div>