code/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
# from rest_framework.aut
from api import views

app_name = 'api'

router = DefaultRouter()

router.register('unitmeasure', viewset=views.UnitMeasureMVS, basename='unitmeasure')
router.register('status', viewset=views.StatusMVS, basename='status')
router.register('people', viewset=views.PeopleMVS, basename='people')
router.register('attachment', viewset=views.AttachmentMVS, basename='attachment')
router.register('partcategory', viewset=views.PartCategoryMVS, basename='partcategory')
router.register('supplier', viewset=views.SupplierMVS, basename='supplier')
router.register('part',viewset=views.PartMVS, basename='part')
router.register('minstock', viewset=views.MinimumStockMVS, basename='minstock')
router.register('currentstock', viewset=views.CurrentStockMVS, basename='currentstock')
router.register('order', viewset=views.OrderMVS, basename='order')
router.register('receiving', viewset=views.ReceivingMVS, basename='receiving')
router.register('dash', viewset=views.Dash, basename='dash')

urlpatterns = [
    path('', include(router.urls)),
    path('schema', get_schema_view(title='ERP API', description='RESTful API for the ERP web application'))
]

from rest_framework.authtoken import views
urlpatterns += [
    path('auth-token/', views.obtain_auth_token)
]

code/erpWa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include('frontend.urls')),
    path('api/', include('api.urls')),
    path('api/docs', include_docs_urls(title="ERP web app API"))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path ('media/<path:path>', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

code/frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from frontend import views


app_name = 'frontend'

urlpatterns = [
    path('logout', views.logoutRedirect, name='logoutRedirect'),
    path('', views.HomePage.as_view(), name='home'),
    path('current', views.CurrentStock.as_view(), name='currentHome'),
    path('current/update', views.CurrentStockUpdate.as_view(), name='currentUpdate'),
    path('current/upload', views.CurrentStockUpload.as_view(), name='currentUpload'),
    path('min', views.MinimumStock.as_view(), name='minHome'),
    path('min/update', views.MinStockUpdate.as_view(), name='minUpdate'),
    path('min/upload', views.MinimumStockUpload.as_view(), name='minUpload'),
    path('purchasing', views.Purchasing.as_view(), name='purchasingHome'),
    path('purchasing/create', views.PurchasingCreate.as_view(),
         name='purchasingCreate'),
    path('purchasing/update/<int:pk>',
         views.PurchaseUpdate.as_view(), name='purchasingUpdate'),
    path('purchasing/close', views.ClosePurchaseOrder.as_view(),
         name='purchasingClose'),
    path('purchasing/open/<int:pk>',
         views.OpenPurchaseOrder.as_view(), name='purchasingOpen'),
    path('purchasing/delete', views.DeletePurchaseOrder.as_view(),
         name='purchaseDelete'),
    path('purchasing/edit', views.EditPurchaseOrder.as_view(), name='purchaseEdit'),

    path('workingonit', TemplateView.as_view(
        template_name='inprogress/underWork.html'), name='inprog'),

    path('test', (TemplateView.as_view(
        template_name='registration/login_test.html')), name='test'),
    path('workingonit', TemplateView.as_view(
        template_name='inprogress/underWork_normal.html'), name='inprog')
]

code/frontend/models.py
from django.db import models

# Create your models here.

code/frontend/views.py
import requests
from utils.utils import csvread
import json
import time
from django.urls import reverse, resolve, reverse_lazy
# from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from utils.apiUtils import api_get, api_auth, api_post, api_patch, api_delete
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
decorators=[never_cache,]

# Create your views here.


def logoutRedirect(request):
    # print(request)
    logout(request=request)
    
    return HttpResponseRedirect(redirect_to=reverse('frontend:home'))

# Homepage

class HomePage(LoginRequiredMixin, View):
    # redirect_field_name = 'redirect_to'
    template_name = 'home/dash.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'module':'Dashboard'}
        
        return render(request, template_name=self.template_name, context=data)

class CurrentStock(LoginRequiredMixin, View):
    template_name = 'current/current.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')
    

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet

       

        data ={
            'dash':dashGet.json(),
            'types':typeGet.json(),
            'module':'Current Stock'}
        
        return render(request, template_name=self.template_name, context=data)

class CurrentStockUpdate(LoginRequiredMixin, View):

    def get(self,request):
        return redirect(to=reverse_lazy('frontend:currentHome'))

    def post(self,request):

        partUrl = request.build_absolute_uri(reverse_lazy('api:part-list'))
        partGet = api_get(url= partUrl, request= request)
        partData = partGet.json()

        updateQuantity = request.POST.getlist('new_quantity')

        apiPostData = []

        for count,val in enumerate(updateQuantity):
            if val != "":
                apiPostData.append({
                    'part': partData[count]['url'],
                    'currentStock': int(val)
                })

        currentStockUrl = request.build_absolute_uri(reverse_lazy('api:currentstock-list'))

        apiPost =api_post(
            url= currentStockUrl,
            data=json.dumps(apiPostData),
            request=request,
            post_content_type='json'
            )
        
        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:currentHome'))

class CurrentStockUpload(LoginRequiredMixin, View):

    def post(self,request):
        
        reader = csvread(request=request,form_handle='file')
        current_post = []
        for row in reader:
            if row[2] != "":
                current_post.append(
                {
                    "part": row[0],
                    "currentStock": row[2]
                }
                )
        current_post.pop(0)
        # print(json.dumps(current_post))
        
        api = request.build_absolute_uri(reverse_lazy('api:currentstock-list'))
        
        apiPost = api_post(url= api, request=request, data= json.dumps(current_post), post_content_type='json')

        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:currentHome'))


class MinimumStock(LoginRequiredMixin, View):
    template_name = 'min/min.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'module':'Minimum Stock'}
        
        return render(request, template_name=self.template_name, context=data)

class MinStockUpdate(LoginRequiredMixin, View):

    def get(self,request):
        return redirect(to=reverse_lazy('frontend:minHome'))

    def post(self,request):
        # print(request.POST)

        partUrl = request.build_absolute_uri(reverse_lazy('api:part-list'))
        partGet = api_get(url= partUrl, request= request)
        partData = partGet.json()

        updateQuantity = request.POST.getlist('new_quantity')

        apiPostData = []

        for count,val in enumerate(updateQuantity):
            if val != "":
                apiPostData.append({
                    'part': partData[count]['url'],
                    'minimumStock': int(val)
                })

        # print(apiPostData)
        minStockUrl = request.build_absolute_uri(reverse_lazy('api:minstock-list'))

        apiPost =api_post(
            url= minStockUrl,
            data=json.dumps(apiPostData),
            request=request,
            post_content_type='json'
            )
        
        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:minHome'))

class MinimumStockUpload(LoginRequiredMixin, View):

    def post(self,request):
        
        reader = csvread(request=request,form_handle='file')
        current_post = []
        for row in reader:
            if row[2] != "":
                current_post.append(
                {
                    "part": row[0],
                    "minimumStock": row[2]
                }
                )
        current_post.pop(0)
        # print(json.dumps(current_post))
        
        api = request.build_absolute_uri(reverse_lazy('api:minstock-list'))
        
        apiPost = api_post(url= api, request=request, data= json.dumps(current_post), post_content_type='json')

        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:minHome'))


class Purchasing(LoginRequiredMixin, View):
    template_name= 'purchasing/main.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')
    orderEndpoint = reverse_lazy('api:order-list')

    def get(self, request):
        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        orderUrl = request.build_absolute_uri(self.orderEndpoint)
        orderGet = api_get(url=orderUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet
        if isinstance(orderGet, HttpResponse):
            return orderGet

        orderData = orderGet.json()

        
        total = len(orderData)
        delivered = 0
        undelivered =0
        for order in orderData:
            if order['dateDelivered']:
                delivered +=1
            elif order['dateDelivered'] is None:
                undelivered +=1
        
        orderSummary={
            'total' : total,
            'delivered' : delivered,
            'undelivered' : undelivered
        }


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'summary':orderSummary, 'module':'Purchasing'}
        
        return render(request, template_name=self.template_name, context=data)

@method_decorator(name='dispatch', decorator=never_cache)
class PurchasingCreate(LoginRequiredMixin,View):
    template_name = 'purchasing/createMain.html'
    orderEndpoint = reverse_lazy('api:order-list')
    partEndpoint = reverse_lazy('api:part-list')

    def get(self,request, extra=None):

        startTime = time.time()
        partUrl = request.build_absolute_uri(self.partEndpoint)
        partGet = api_get(url= partUrl, request=request)

        orderUrl = request.build_absolute_uri(self.orderEndpoint)
        orderGet =api_get(url=orderUrl, request=request)


        if isinstance(partGet, HttpResponse):
            return partGet

        if isinstance(orderGet, HttpResponse):
            return orderGet
        
        partData = partGet.json()
        orderData = orderGet.json()

        for dict in orderData:
            for pdict in partData:
                if pdict['url']== dict['part']:
                    dict['partName']= pdict['name']
            # print(dict['partName'])                

        
        data={
            'parts': partData,
            'orders': orderData
        }

        # print('!!!!!>>> Time: ', (time.time()-startTime))

code/frontend/templates/purchasing/createMain.html
{%extends 'base/base.html'%}
{%block main_content%}
{%load static%}

<style>
    .orderLink:hover {
        background-color: lightgray;
    }

</style>

<div class="row p-2" style="height:100% ; overflow-y: auto;">
    <form method="post">
        {%csrf_token%}
    <div class="col-lg-12">
        <div class="row" style="height:45vh ;">
            <div class="col-lg-6 p-2 ">
                <div class="d-grid shadow_box gap-4 p-3">
                    <div class="display-5">Create Order</div>
                    <div class="row">
                        <div class="col">
                            <label for="ponumber" class="h4">PO number</label>
                        </div>
                        <div class="col">
                            <input type="number" name="ponumber" id="ponumber">
                        </div>
                    </div>
    
                    <div class="row">
                        <div class="col">
                            <label for="date_ordered" class="h4">Date Ordered</label>
                        </div>
                        <div class="col">
                            <input type="date" name="date_ordered" id="date_ordered">
                        </div>
                    </div>
    
                    <div class="row">
                        <div class="col">
                            <label for="eta" class="h4">Expected Delivery Date</label>
                        </div>
                        <div class="col">
                            <input type="date" name="eta" id="eta">
                        </div>
                    </div>
    
                    <div class="row">
                        <div class="col-sm-2">
                            <input type="submit" value="Create" class="btn btn-lg btn-primary">
                        </div>
                    </div>
    
                </div>
            </div>
            <div class="col-lg-6 p-2">
                <div class="d-grid shadow_box gap-4 p-3">
                    <div class="display-5">Select Parts</div>
    
                    <div>
                        <table class="table table-responsive" id="order_table">
                            <thead>
                                <th>#</th>
                                <th>Part</th>
                                <th>Quantity</th>
                                <th></th>
                                
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="t_id">1</td>
                                    <td id="to_part">
                                        <select name="part" id="part">
                                            <option value="" disabled selected hidden></option>
    
                                            {%for obj in parts%}
                                            <option value={{obj.url}}>{{obj.name}}</option>
                                            {%endfor%}
                                        </select>
    
                                    </td>
                                    <td id="to_quant">
                                        <input type="number" name="quantity">
                                    </td>
                                    <td id="del" style="display: none;">
                                        <img src={%static 'purchasing/red_minus.png'%} alt="" width="30px"  onclick="delRow()" style="cursor:pointer ;">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="btn btn-secondary" onclick="addRow()">Add more</button>
                        </div>
                    </div>
                </div>
            </div>
            
        </form>
        <div class="row shadow_box m-2 mr-3" style="height:auto ;">
            <div class="col-lg-12">
                <div class="display-5 stickAtTop">All Orders</div>
            <table class="table table-responsive">
                <thead style="position: sticky; top:3.5rem ;">
                    <th>#</th>
                    <th>PO Number</th>
                    <th>Part</th>
                    <th>Quantity</th>
                    <th>Date Ordered</th>
                    <th>ETA</th>
                    <th>Status</th>
                </thead>
                <tbody>
                    {%for order in orders%}
                    
                    <tr class="orderLink" onclick="updateOrder('{{order.id}}')" style="cursor:pointer; ">
                        <td>{{order.id}}
                            <a href={%url 'frontend:purchasingUpdate' order.id %} id="link_{{order.id}}" ></a>
                        </td>
                        <td>{{order.poNumber}}</td>
                        <td>{{order.partName}}</td>
                        <td>{{order.quantity}}</td>
                        <td>{{order.dateOrdered}}</td>
                        <td>{%if order.dateDelivered%}
                            <strong>Delivered</strong>
                            {%else%}
                            {{order.eta}}
                            {%endif%}
                        </td>
                        <td>{%if order.status|slice:'-2:-1' == "2" %}
                            <span class="text-primary">
                                <strong>
                                    Closed
                                </strong>
                            </span>
                            {%elif order.status|slice:'-2:-1' == "1" %}
                            <span class="text-warning">
                                <strong>
                                    Open
                                </strong>
                            </span>
                            {%endif%}
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>

            </table>
            </div>
            
        </div>
    </div>
</div>



<script type="text/javascript">

let idSeries = 2;
let table = document.getElementById("order_table");
let id = document.getElementsByClassName("t_id");
let selectPart = document.getElementById("to_part");
let quantity = document.getElementById("to_quant");
let del = document.getElementById("del");





function addRow() {

    let newRow = table.insertRow(-1);
    let cell1 = newRow.insertCell(0);
    let cell2 = newRow.insertCell(1);
    let cell3 = newRow.insertCell(2);
    let cell4 = newRow.insertCell(3);

    cell1.innerHTML = String(idSeries);
    cell2.innerHTML = selectPart.innerHTML;
    cell3.innerHTML = quantity.innerHTML;
    cell4.innerHTML = del.innerHTML;

    idSeries +=1;

}

function delRow() {
    event.srcElement.parentElement.parentElement.remove()
    idSeries -= 1;
}

function updateOrder(pk) {
    linkID = `link_${pk}`
    link = document.getElementById(linkID)
    console.log(link.href)
    window.location.href = link.href
}

</script>
{%endblock main_content%}

code/frontend/templates/purchasing/main.html
{%extends 'base/base.html'%}
{%block main_content%}
    <div class="row row_filter">
        <div class="col-lg-6 col_filter d-grid gap-2">
            {%include 'purchasing/filters.html'%}
        </div>
    </div>
    <div class="row row_content">
        <div class="col-lg-6 col_content">
            {%include 'purchasing/table.html'%}
        </div>
        <div class="col-lg-5 col_content m-2" style="height: fit-content;">
            {%include 'purchasing/summary.html'%}
        </div>
        
    </div>
{%endblock main_content%}

code/frontend/templates/purchasing/table.html
<table class="table table-dash">
    <thead>
        <th>Id</th>
        <th>Part Name</th>
        <th>Category</th>
        <th>Ordered quantity</th>

    </thead>
    <tbody>
        
            {%for inst in dash%}
            {%if inst.onorder%}
            <tr class="table_row">
                <td class="t_id">{{inst.id}}</td>
                <td class="t_part_name">{{inst.name}}</td>
                <td class="t_part_type">{{inst.category | capfirst}}</td>
                <td class="t_current_stock">{{inst.onorder}}</td>
            </tr>
            
            {%endif%}
                
            {%endfor%}
            

        </form>

    </tbody>
    
        

</table>

code/frontend/templates/purchasing/update.html
{%extends 'base/base.html'%}
{%block main_content%}

{%if order.dateDelivered%}
        <meta http-equiv="refresh" content="0; URL={%url 'frontend:purchasingOpen' order.id%}">
{%endif%}

<div class="row p-2">
    <div class="col-lg-12 shadow_box">
        <div class="display-6">
            Purchase Order#: {{order.poNumber}} | Part: {{part.name}}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <form action="" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <input type="hidden" name="o_quantity" value="{{order.quantity}}">
            <input type="hidden" name="o_received" value="{{order.received}}">
            <input type="hidden" name="o_url" value="{{order.url}}">
            <input type="hidden" name="o_part" value="{{order.part}}">
            <input type="hidden" name="o_part_name" value="{{part.name}}">
        <div class="shadow_box d-grid gap-2 p-4">
                <div class="display-5 ">Receiving</div>
                <div class="row">
                    <div class="col-sm-6 h4">
                        <label for="r_completed_id">Order Complete?</label>
                    </div>
                    <div class="col-sm-6">
                        <select name="r_completed" id="r_completed_id" onchange="complete_check()" class="form-select">
                            <option value="0" selected>No</option>
                            <option value="1" >Yes</option>
                        </select>
                    </div>
                </div>
        
                <div  id="forhiding">
                    <div class="d-grid gap-2">

                        <div class="row">
                            <div class="col-sm-6 h4">
                                <label for="r_received_id">Quantity Received</label>
                            </div>
                            <div class="col-sm-6">
                                <input required type="number" id="r_received_id" class="form-control" name="r_received" >
                            </div>
                        </div>
            
                        <div class="row " >
                            <div class="col-sm-6 h4">
                                <label for="r_attachment_id">Attachment</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="file" id="r_attachment_id" name="r_attachment" class="form-control">
                            </div>
                        </div>
                
                        <div class="row " >
                            <div class="col-sm-6 h4">
                                <label for="r_data_rec_id">Date Received</label>
                            </div>
                            <div class="col-sm-6">
                                <input required class="form-control" type="date" name="r_date_received" id="r_data_rec_id">
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row " id="datedeliv_row" style="display: none;">
                    <div class="col-sm-6 h4">
                        <label for="r_data_deliv_id">Date of fulfillment</label>
                    </div>
                    <div class="col-sm-6">
                        <input class="form-control" type="date" name="r_date_delivered" id="r_data_deliv_id" form="order_close" required>
                    </div>
                </div>
        
    
                <div class="row">
                    <div class="col-lg-4">
                        <button class="btn btn-primary btn-lg" type="submit" id="r_button">Submit</button>    
                    </form>
                        <form action="{%url 'frontend:purchasingClose'%}" method="post" id="order_close">
                            {%csrf_token%}
                            <input type="hidden" name="close_url" value="{{order.url}}">
                            <input type="hidden" name="close_part" value="{{order.part}}">
                            <input type="hidden" name="close_part_name" value="{{part.name}}">
                            <input type="hidden" name="close_order_quantity" value="{{order.quantity}}">
                            <input type="hidden" name="close_status" value="closed">
                            <input type="hidden" name="redirect_pk" value="{{order.id}}">
                            <button class="btn btn-warning btn-lg" type="submit" id="close_button" style="display:none ;">Close order</button>
                        </form>
                    </div>
                </div>

        </div>
    </div>
    <div class="col-lg-6">
        <form action="{%url 'frontend:purchaseEdit'%}" method="post">
            {%csrf_token%}
            <input type="hidden" name="e_url" value="{{order.url}}">

            <div class="shadow_box d-grid gap-2 p-4">
    
                <div class="display-5">Update Order</div>
                <div class="row">
                    <div class="col-sm-6 h4">
                        <label for="e_ponumber">PO Number</label>
                    </div>
                    <div class="col-sm-6">
                        <input type="number" id="e_ponumber" name="e_ponumber" placeholder="{{order.poNumber}}">
                    </div>
                </div>
        
                <div class="row">
                    <div class="col-sm-6 h4">
                        <label for="e_part">Part</label>
                    </div>
                    <div class="col-sm-6">
                        <select name="e_part" id="e_part">
                            <option value="{{part.url}}"  selected >{{part.name}}</option>

                            {%for obj in partlist%}
                            <option value='{{obj.url}}'>{{obj.name}}</option>
                            {%endfor%}
                        </select>
                    </div>
                </div>
        
                <div class="row">
                    <div class="col-sm-6 h4">
                        <label for="e_quantity">Quantity Ordered</label>
                    </div>
                    <div class="col-sm-6">
                        <input type="number" id="e_quantity" name="e_quantity" placeholder="{{order.quantity}}">
                    </div>
                </div>
        
                <div class="row">
                    <div class="col-sm-6 h4">
                        <label for="e_eta">ETA</label>
                    </div>
                    <div class="col-sm-6">
                        <input type="date" id="e_eta"  name="e_eta">
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-2">
                        <button class="btn btn-primary btn-lg" type="submit">Update</button>
                            
                    </form>
                    </div>
                    <div class="col-sm-2">
                        <form action="{%url 'frontend:purchaseDelete'%}" method="post">
                            {%csrf_token%}
                            <input type="hidden" name="d_url" value="{{order.url}}">
                            <button class="btn btn-danger btn-lg">Delete</button>
                        </form>
                    </div>
                </div>

            </div>
    </div>
</div>

<!-- <div class="row bg-secondary" style="height:100% ; ">
    <div class="col-lg-12 bg-primary d-grid gap-2">
        <div class="display-5">Receiving Records</div>
        <table class="table ">
            <thead>
                <th>#</th>
                <th>#</th>
                <th>#</th>
                <th>#</th>
            </thead>
            
            <tbody>
                <tr>
                    <td>test</td>
                    <td>test</td>
                    <td>test</td>
                    <td>test</td>
                </tr>
            </tbody>
        </table>
    </div>

</div> -->

<script type="text/javascript">
    
    let dateDelivered = document.getElementById("datedeliv_row");
    let complete = document.getElementById("r_completed_id");
    let block = document.getElementById("forhiding");
    let submit = document.getElementById("r_button")
    let c_button =document.getElementById("close_button");
    let stillOnOrder = parseInt("{{order.quantity}}") -( parseInt("{{order.received}}") || 0);
    let quantityInput = document.getElementById("r_received_id");
    quantityInput.setAttribute('placeholder', stillOnOrder);
    

    function complete_check() {
        if (complete.value == 1){
            block.style.display = "none";
            c_button.style.display = "block";
            submit.style.display ="none";
            dateDelivered.style.display = "block";
            
        }

        else if (complete.value == 0) {
            block.style.display = "block";
            c_button.style.display = "none";
            submit.style.display ="block"
            dateDelivered.style.display = "none";
        }
        
    }

    


</script>

{%endblock main_content%}