code/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
# from rest_framework.aut
from api import views

app_name = 'api'

router = DefaultRouter()

router.register('unitmeasure', viewset=views.UnitMeasureMVS, basename='unitmeasure')
router.register('status', viewset=views.StatusMVS, basename='status')
router.register('people', viewset=views.PeopleMVS, basename='people')
router.register('attachment', viewset=views.AttachmentMVS, basename='attachment')
router.register('partcategory', viewset=views.PartCategoryMVS, basename='partcategory')
router.register('supplier', viewset=views.SupplierMVS, basename='supplier')
router.register('part',viewset=views.PartMVS, basename='part')
router.register('minstock', viewset=views.MinimumStockMVS, basename='minstock')
router.register('currentstock', viewset=views.CurrentStockMVS, basename='currentstock')
router.register('order', viewset=views.OrderMVS, basename='order')
router.register('receiving', viewset=views.ReceivingMVS, basename='receiving')
router.register('dash', viewset=views.Dash, basename='dash')

urlpatterns = [
    path('', include(router.urls)),
    path('schema', get_schema_view(title='ERP API', description='RESTful API for the ERP web application'))
]

from rest_framework.authtoken import views
urlpatterns += [
    path('auth-token/', views.obtain_auth_token)
]

code/erpWa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', include('frontend.urls')),
    path('api/', include('api.urls')),
    path('api/docs', include_docs_urls(title="ERP web app API"))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path ('media/<path:path>', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

code/frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from frontend import views


app_name = 'frontend'

urlpatterns = [
    path('logout', views.logoutRedirect, name='logoutRedirect'),
    path('', views.HomePage.as_view(), name='home'),
    path('current', views.CurrentStock.as_view(), name='currentHome'),
    path('current/update', views.CurrentStockUpdate.as_view(), name='currentUpdate'),
    path('current/upload', views.CurrentStockUpload.as_view(), name='currentUpload'),
    path('min', views.MinimumStock.as_view(), name='minHome'),
    path('min/update', views.MinStockUpdate.as_view(), name='minUpdate'),
    path('min/upload', views.MinimumStockUpload.as_view(), name='minUpload'),
    path('purchasing', views.Purchasing.as_view(), name='purchasingHome'),
    path('purchasing/create', views.PurchasingCreate.as_view(),
         name='purchasingCreate'),
    path('purchasing/update/<int:pk>',
         views.PurchaseUpdate.as_view(), name='purchasingUpdate'),
    path('purchasing/close', views.ClosePurchaseOrder.as_view(),
         name='purchasingClose'),
    path('purchasing/open/<int:pk>',
         views.OpenPurchaseOrder.as_view(), name='purchasingOpen'),
    path('purchasing/delete', views.DeletePurchaseOrder.as_view(),
         name='purchaseDelete'),
    path('purchasing/edit', views.EditPurchaseOrder.as_view(), name='purchaseEdit'),

    path('workingonit', TemplateView.as_view(
        template_name='inprogress/underWork.html'), name='inprog'),

    path('test', (TemplateView.as_view(
        template_name='registration/login_test.html')), name='test'),
    path('workingonit', TemplateView.as_view(
        template_name='inprogress/underWork_normal.html'), name='inprog')
]

code/frontend/models.py
from django.db import models

# Create your models here.

code/frontend/views.py
import requests
from utils.utils import csvread
import json
import time
from django.urls import reverse, resolve, reverse_lazy
# from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from utils.apiUtils import api_get, api_auth, api_post, api_patch, api_delete
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
decorators=[never_cache,]

# Create your views here.


def logoutRedirect(request):
    # print(request)
    logout(request=request)
    
    return HttpResponseRedirect(redirect_to=reverse('frontend:home'))

# Homepage

class HomePage(LoginRequiredMixin, View):
    # redirect_field_name = 'redirect_to'
    template_name = 'home/dash.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'module':'Dashboard'}
        
        return render(request, template_name=self.template_name, context=data)

class CurrentStock(LoginRequiredMixin, View):
    template_name = 'current/current.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')
    

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet

       

        data ={
            'dash':dashGet.json(),
            'types':typeGet.json(),
            'module':'Current Stock'}
        
        return render(request, template_name=self.template_name, context=data)

class CurrentStockUpdate(LoginRequiredMixin, View):

    def get(self,request):
        return redirect(to=reverse_lazy('frontend:currentHome'))

    def post(self,request):

        partUrl = request.build_absolute_uri(reverse_lazy('api:part-list'))
        partGet = api_get(url= partUrl, request= request)
        partData = partGet.json()

        updateQuantity = request.POST.getlist('new_quantity')

        apiPostData = []

        for count,val in enumerate(updateQuantity):
            if val != "":
                apiPostData.append({
                    'part': partData[count]['url'],
                    'currentStock': int(val)
                })

        currentStockUrl = request.build_absolute_uri(reverse_lazy('api:currentstock-list'))

        apiPost =api_post(
            url= currentStockUrl,
            data=json.dumps(apiPostData),
            request=request,
            post_content_type='json'
            )
        
        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:currentHome'))

class CurrentStockUpload(LoginRequiredMixin, View):

    def post(self,request):
        
        reader = csvread(request=request,form_handle='file')
        current_post = []
        for row in reader:
            if row[2] != "":
                current_post.append(
                {
                    "part": row[0],
                    "currentStock": row[2]
                }
                )
        current_post.pop(0)
        # print(json.dumps(current_post))
        
        api = request.build_absolute_uri(reverse_lazy('api:currentstock-list'))
        
        apiPost = api_post(url= api, request=request, data= json.dumps(current_post), post_content_type='json')

        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:currentHome'))


class MinimumStock(LoginRequiredMixin, View):
    template_name = 'min/min.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')

    def get(self,request):

        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'module':'Minimum Stock'}
        
        return render(request, template_name=self.template_name, context=data)

class MinStockUpdate(LoginRequiredMixin, View):

    def get(self,request):
        return redirect(to=reverse_lazy('frontend:minHome'))

    def post(self,request):
        # print(request.POST)

        partUrl = request.build_absolute_uri(reverse_lazy('api:part-list'))
        partGet = api_get(url= partUrl, request= request)
        partData = partGet.json()

        updateQuantity = request.POST.getlist('new_quantity')

        apiPostData = []

        for count,val in enumerate(updateQuantity):
            if val != "":
                apiPostData.append({
                    'part': partData[count]['url'],
                    'minimumStock': int(val)
                })

        # print(apiPostData)
        minStockUrl = request.build_absolute_uri(reverse_lazy('api:minstock-list'))

        apiPost =api_post(
            url= minStockUrl,
            data=json.dumps(apiPostData),
            request=request,
            post_content_type='json'
            )
        
        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:minHome'))

class MinimumStockUpload(LoginRequiredMixin, View):

    def post(self,request):
        
        reader = csvread(request=request,form_handle='file')
        current_post = []
        for row in reader:
            if row[2] != "":
                current_post.append(
                {
                    "part": row[0],
                    "minimumStock": row[2]
                }
                )
        current_post.pop(0)
        # print(json.dumps(current_post))
        
        api = request.build_absolute_uri(reverse_lazy('api:minstock-list'))
        
        apiPost = api_post(url= api, request=request, data= json.dumps(current_post), post_content_type='json')

        if isinstance(apiPost, HttpResponse):
            return apiPost

        return redirect(to=reverse_lazy('frontend:minHome'))


class Purchasing(LoginRequiredMixin, View):
    template_name= 'purchasing/main.html'
    dashEndpoint = reverse_lazy('api:dash-list')
    typeEndpoint = reverse_lazy('api:partcategory-list')
    orderEndpoint = reverse_lazy('api:order-list')

    def get(self, request):
        dashUrl = request.build_absolute_uri(self.dashEndpoint)
        dashGet = api_get(url= dashUrl, request= request)
        # print(dashGet.status_code)

        typeUrl = request.build_absolute_uri(self.typeEndpoint)
        typeGet = api_get(url=typeUrl, request=request)

        orderUrl = request.build_absolute_uri(self.orderEndpoint)
        orderGet = api_get(url=orderUrl, request=request)

        if isinstance(dashGet, HttpResponse):
            return dashGet
        if isinstance(typeGet, HttpResponse):
            return typeGet
        if isinstance(orderGet, HttpResponse):
            return orderGet

        orderData = orderGet.json()

        
        total = len(orderData)
        delivered = 0
        undelivered =0
        for order in orderData:
            if order['dateDelivered']:
                delivered +=1
            elif order['dateDelivered'] is None:
                undelivered +=1
        
        orderSummary={
            'total' : total,
            'delivered' : delivered,
            'undelivered' : undelivered
        }


        data ={'dash':dashGet.json(), 'types':typeGet.json(), 'summary':orderSummary, 'module':'Purchasing'}
        
        return render(request, template_name=self.template_name, context=data)

@method_decorator(name='dispatch', decorator=never_cache)
class PurchasingCreate(LoginRequiredMixin,View):
    template_name = 'purchasing/createMain.html'
    orderEndpoint = reverse_lazy('api:order-list')
    partEndpoint = reverse_lazy('api:part-list')

    def get(self,request, extra=None):

        startTime = time.time()
        partUrl = request.build_absolute_uri(self.partEndpoint)
        partGet = api_get(url= partUrl, request=request)

        orderUrl = request.build_absolute_uri(self.orderEndpoint)
        orderGet =api_get(url=orderUrl, request=request)


        if isinstance(partGet, HttpResponse):
            return partGet

        if isinstance(orderGet, HttpResponse):
            return orderGet
        
        partData = partGet.json()
        orderData = orderGet.json()

        for dict in orderData:
            for pdict in partData:
                if pdict['url']== dict['part']:
                    dict['partName']= pdict['name']
            # print(dict['partName'])                

        
        data={
            'parts': partData,
            'orders': orderData
        }

        # print('!!!!!>>> Time: ', (time.time()-startTime))

code/frontend/templates/base/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'base/base.css' %}">
    
    
</head>
<body>
    <div class="container-fluid container_main">
        <div  class="row row_1">
            <div class="col-sm-2 firm_name">w-ERP</div>
            <div class="col-sm-4 offset-sm-2 display-6 text-center text-white">{{module}}</div>
        </div>
        <div class="row row_2">
            <div class="col-lg-1 fixed-left d-flex justify-content-center align-items-top">
                {%include 'base/menu.html'%}
            </div>
            <div class="col-lg-11 fixed-right">
                {%block main_content%}
                {%endblock main_content%}
            </div>
        </div>
    </div>
    
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</html>

code/frontend/templates/base/menu.html
<div class="accordion w-100" id="menu_accordion"  >
    <div class="accordion-item">
        <h2 class="accordion-header" id="accordion_home">
          <a href="{%url 'frontend:home'%}" style="text-decoration: none;">
            <div class="d-grid gap-2" data-bs-toggle="collapse">
                <button class="btn btn-success" type="button"><strong>Home</strong></button>
            </div>
          </a>
        </h2>
    </div>
    
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne" data-target="">
            
                <strong> Inventory</strong>
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#menu_accordion">
            <div class="accordion-body-fluid p-2">
                <div class="d-grid gap-2">
                    
                    <div><a href="{%url 'frontend:currentHome'%}"><button class="btn btn-outline-primary w-100">Current Stock</button></a></div>
                    <div><a href="{%url 'frontend:minHome'%}"><button class="btn btn-outline-primary w-100">Minimum Stock</button></a></div>
                    <!-- <div><a href="{%url 'frontend:purchasingHome'%}"><button class="btn btn-outline-primary w-100">Purchasing</button></a></div> -->
                    
                </div>
            </div>
        </div>
    </div>

    <div class="accordion-item">
      <h2 class="accordion-header" id="headingPur">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapsePur" aria-expanded="false" aria-controls="collapsePur" data-target="">
          
              <strong>Purchasing</strong>
          </button>
      </h2>
      <div id="collapsePur" class="accordion-collapse collapse" aria-labelledby="headingPur" data-bs-parent="#menu_accordion">
          <div class="accordion-body-fluid p-2">
              <div class="d-grid gap-2">
                  
                  
                  <div><a href="{%url 'frontend:purchasingHome'%}"><button class="btn btn-outline-primary w-100">Orders Overview</button></a></div>
                  <div><a href="{%url 'frontend:purchasingCreate'%}"><button class="btn btn-outline-primary w-100">Create-Update</button></a></div>
              </div>
          </div>
      </div>
  </div>

    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <strong>Production</strong>
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#menu_accordion">
        <div class="accordion-body-fluid p-2">
            <div class="d-grid gap-2">
                
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">Projects</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">Shipment</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">Allocations</button></a></div>
                
            </div>
        </div>
      </div>
    </div>
    <!-- <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            <strong>Planning</strong>
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#menu_accordion">
        <div class="accordion-body-fluid p-2">
            <div class="d-grid gap-2">
                
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">Utilization</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">Expected</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">Forecast</button></a></div>
                
            </div>
        </div>
      </div>  
    </div> -->

    <!-- <div class="accordion-item">
      <h2 class="accordion-header" id="headingFour">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
            <strong>Quotation</strong>
        </button>
      </h2>
      <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#menu_accordion">
        <div class="accordion-body-fluid p-2">
            <div class="d-grid gap-2">
                
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                
            </div>
        </div>
      </div>
    </div> -->

    <!-- <div class="accordion-item">
      <h2 class="accordion-header" id="headingFive">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
            <strong>Reports</strong>
        </button>
      </h2>
      <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#menu_accordion">
        <div class="accordion-body-fluid p-2">
            <div class="d-grid gap-2">
                
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                
            </div>
        </div>
      </div>
    </div> -->

    <!-- <div class="accordion-item">
      <h2 class="accordion-header" id="headingSix">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
            <strong>Settings</strong>
        </button>
      </h2>
      <div id="collapseSix" class="accordion-collapse collapse" aria-labelledby="headingSix" data-bs-parent="#menu_accordion">
        <div class="accordion-body-fluid p-2">
            <div class="d-grid gap-2">
                
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                <div><a href="{%url 'frontend:inprog'%}"><button class="btn btn-outline-primary w-100">tbd</button></a></div>
                
            </div>
        </div>
      </div>
    </div> -->

    <div class="accordion-item">
      <h2 class="accordion-header" id="headingSeven">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
            <strong>Profile</strong>
        </button>
      </h2>
      <div id="collapseSeven" class="accordion-collapse collapse" aria-labelledby="headingSeven" data-bs-parent="#menu_accordion">
        <div class="accordion-body-fluid p-2">
            <div class="d-grid gap-2">
                <div class="h4 text-wrap text-center">Welcome!!</div>
                <div class="h4 text-wrap text-center">{{request.user.first_name}}</div>
                <div><a href="#"><button class="btn btn-outline-primary w-100">Details</button></a></div>
                <div><a href="{% url 'admin:index' %}"><button class="btn btn-outline-primary w-100">Admin</button></a></div>
                <div><a href="{%url 'frontend:logoutRedirect'%}"><button class="btn btn-danger w-100">LogOut</button></a></div>
                
            </div>
        </div>
      </div>        
    </div>
    
</div>